package com.tasknotification.tasknotification.controller;

public enum Codes {
    SUCCESS,
    VALIDATION_ERR,
    EXISTING_EMAIL,
    UNKNOWN_ERROR,
    REQUEST_PARAMS_EMPTY,
    LOGIN_FAILED,
    TERM_IS_NOT_VALID,
    INACTIVE_SESSION_ID,
    OBJECT_CHAR_INCORRECT,
    EXISTING_OBJECT_AT_SUBORDINATE,
    MESSAGE_CHAR_INCORRECT,
    GRACE_PERIOD_INCORRECT,
    NOT_EXIST_SUBORDINATE_ID;
}
